theme: jekyll-theme-minimal
github: is\_project\_page:false
title: Hi, I'm Sophie He.
description: Shanghai-born essayist, copywriter, and teacher from Los Angeles. Currently living and writing in St. Louis, MO.
includes:
  - reaction.md
  - fx.md
  - netflix.md
  - mediatemple.md
  - campaigns.md
