theme: jekyll-theme-minimal
github: is\_project\_page:false
title: Hi, I'm Sophie He.
description: Shanghai-born writer from Los Angeles. Junior Fellow at Washington University in St. Louis, where I teach creative writing.
